" kmrhb vimrc

set nocompatible               " be iMproved 

" initialise vundle
filetype on                    " workaround for issue with default OS X vim version
filetype off                   " required for vundle

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" make vundle use git protocol
let g:vundle_default_git_proto = 'git'

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" enable syntax highlighting
syntax on
set cursorline

" bundles
Bundle 'altercation/vim-colors-solarized'

" set colorscheme
set background=dark
colorscheme solarized

" detect filetypes -- required after bundles for vundle
filetype plugin indent on
