" kmrhb vimrc

set nocompatible               " be iMproved 

" initialise vundle
filetype on                    " workaround for issue with default OS X vim version
filetype off                   " required for vundle

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" make vundle use git protocol
let g:vundle_default_git_proto = 'git'

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" disable cursor blink in gui
set guicursor+=a:blinkon0

" setup highlighting
set cursorline

" allow backspace to delete past start of insert
set backspace=indent,eol,start"

" configure vim-slime to use tmux
let g:slime_target = "tmux"

" bundles
Bundle 'altercation/vim-colors-solarized'
Bundle 'jpalardy/vim-slime'
Bundle 'vim-coffee-script'
Bundle 'SirVer/ultisnips'
Bundle 'ervandew/supertab'
Bundle 'michaeljsmith/vim-indent-object'
Bundle 'Raimondi/delimitMate'
Bundle 'kien/ctrlp.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-unimpaired'
Bundle 'scrooloose/syntastic'
Bundle 'scrooloose/nerdcommenter'
Bundle 'Lokaltog/vim-powerline'

" indenting
" default to tab only indenting
set noexpandtab
set shiftwidth=2
set tabstop=2

" set colorscheme
set background=dark
colorscheme solarized

" toggle pastemode
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

" UltiSnips
" configure trigger to be tab / s-tab
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"

let g:UltiSnipsEditSplit="horizontal"

set laststatus=2

" detect filetypes -- required after bundles for vundle
filetype plugin indent on
syntax on
